### ISSUE TITLE
The pre-training model download link in the code has failed

### ISSUE THREAD

**Issue by tzxiang** [shuochsu/DeepEnd2EndToFImaging#2]
Nice work! When I used your code, I found that the pre-training model download link in the code has failed. Could you please upload the pre-training models? Thanks a lot.

**Comment by shuochsu** [comment]
Thanks for your interest in our work. The command has only been tested on a Linux machine. The alternative is to download the model from http://www.cs.ubc.ca/labs/imager/tr/2018/DeepEnd2EndToFImaging/models/my_resnet_lite_my_imageGAN_128.t7, renamed it as latest_net_G.t7, and move it to /checkpoint/my_resnet_lite_my_imageGAN_128_pretrained.
