### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lss11005** [shuochsu/DeepEnd2EndToFImaging#4]
How to download the dataset and model? when I run the XXX.sh, there are no result and when I click the link http://www.cs.ubc.ca/labs/imager/tr/2018/DeepEnd2EndToFImaging/datasets/$FILE.zip
The webpage shows that
 "The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.
Error 404
www.cs.ubc.ca
Apache/2.4.23 (Linux/SUSE)"

**Comment by lss11005** [comment]
Thanks, I think I found the correct download method~

**Comment by shuochsu** [comment]
Hi, this seems to be a common problem with non-linux systems. Can you try to replace $FILE with the command line argument and download again?
